### ISSUE TITLE
Add support for descriptions

### ISSUE THREAD

**Issue by milleniumfrog** [preply/graphene-federation#31]
The graphql type descriptions get lost when I use graphene-federation.
The discription is present in the GraphiQL from the graphql microservice but not in the Graphql Playground of the apollo gateway.
If I implement the Graphql microservice with the apollo server everything works fine.

**Comment by noelleleigh** [comment]
I believe the issue actually lies with [graphene](https://github.com/graphql-python/graphene), rather than this project. [graphql-core](https://github.com/graphql-python/graphql-core) only recently [added support for descriptions](https://github.com/graphql-python/graphql-core/commit/dceb5cdd61ba8676de6492c21cd2057c8fb24a6c) in the generated SDL, and that change won't appear in graphene until v3 is released ([now in beta](https://github.com/graphql-python/graphene/issues/1127)). 

Once the new major version of graphene is released, the descriptions ought to become available for federation.

**Comment by SaulTigh** [comment]
hey, sorry for delay with reply. yes, this is mainly graphene job to generate descriptions. recently we published 0.2.0 which takes 1 step closer to support graphene v3 (probably it already works ok, but we haven't had time to verify that with proper testing)

closing this thread as it seems to be resolved
